###
# Information de base.
###

# Titre du site web.
title: Accueil aux réfugiés St-Yves

# Nom de l'organisation.
organisation: Comité d'accueil aux réfugiés St-Yves

# Nom de l'organisation.
email: accueil@carsy.org

# SEO (Référencement)
url: http://www.carsy.org/
lang: fr
logo: img/logos/icon.png
description: >
  La mission du Comité d’accueil aux réfugiés Saint-Yves consiste à parrainer des réfugiés en état de détresse et plus particulièrement à aider des Québécois à faire venir leurs parents réfugiés et à les accompagner dans leur intégration au sein de la communauté. Il s’agit du plus ancien organisme de parrainage privé toujours actif dans la région de Québec.

# Adresse.
address:
  - Presbytère Saint-Yves
  - 2470 Rue Triquet
  - Québec (Québec) G1W 1E2

###
# Configuration.
###
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
